import { junWords } from './story-fixtures';
import { test, expect } from '@playwright/test';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
import { existsSync } from 'node:fs';
import {
  chooseDinner, chooseWalk, closeDialogue, depart, dialogue, expectClock,
  expectJun, expectHomeScene, expectPhase, expectSceneAssets, openAction, openOptions, openPlanner,
  returnHome, showcase, startStory,
} from './story-helpers';

const artifact = path.resolve('artifacts/crossing-lives-portable.html');

test('portable production file keeps both cities, Jun, choices and quiet resume fully offline', async ({ page, context }) => {
  test.setTimeout(90_000);
  expect(existsSync(artifact), 'Run npm run export:portable before browser verification.').toBe(true);
  await page.setViewportSize({ width: 1440, height: 900 });
  const errors: string[] = [];
  const requests: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  context.on('request', request => { if (/^https?:\/\//i.test(request.url())) requests.push(request.url()); });
  await context.setOffline(true);
  await page.goto(pathToFileURL(artifact).href);
  await startStory(page);
  const allAssetsEmbedded = async () => {
    const images = page.locator('img');
    expect(await images.count()).toBeGreaterThan(0);
    for (const image of await images.all()) {
      await expect(image).toHaveAttribute('src', /^data:image\/webp;base64,/);
      await expect.poll(() => image.evaluate(async (element: HTMLImageElement) => {
        try { await element.decode(); } catch { return false; }
        return element.complete && element.naturalWidth > 0 && element.naturalHeight > 0;
      })).toBe(true);
    }
    expect(requests, 'The portable file must not even attempt HTTP(S).').toEqual([]);
  };
  await expectSceneAssets(page, 'hong-kong-evening.webp', true);
  await allAssetsEmbedded();
  await depart(page, 'Hong Kong');
  await expectSceneAssets(page, 'hong-kong-table.webp', true);
  await expectJun(page, true);
  await allAssetsEmbedded();
  await openAction(page, 'Open phone');
  await expect(page.locator('.route-note-forecast')).toContainText('modeled home 19:15');
  await expect(page.locator('.route-note-condition')).toHaveText('Conditional plan');
  await expect(page.locator('.route-loop-crossing')).toHaveCount(0);
  // Full assumptions are now a visible disclosure, not default summary copy.
  await page.getByRole('button', { name: 'Evening assumptions', exact: true }).click();
  await expect(page.locator('.route-note-detail')).toBeVisible();
  await expect(page.locator('.route-note-detail')).toContainText('60-minute simple dinner · assumed, still to choose');
  await expect(page.locator('.route-note-detail')).toContainText('45-minute walk · assumed, still to choose');
  await expect(page.locator('.route-note-detail')).toContainText('disclosed 30-minute dinner delay');
  await page.getByRole('button', { name: /^Coming home/ }).click();
  await expect(page.locator('.route-note-legs li')).toHaveCount(1);
  await expect(page.locator('.route-note-legs')).toContainText('Local return journey');
  await allAssetsEmbedded();
  await closeDialogue(page);
  await chooseDinner(page, 'linger');
  await expectSceneAssets(page, 'hong-kong-table.webp', true);
  await allAssetsEmbedded();
  await chooseWalk(page, 'long');
  await expectSceneAssets(page, 'hk-evening-night.webp', true);
  await expectJun(page, true);
  await allAssetsEmbedded();
  await closeDialogue(page);
  await showcase(page, 'portable-hk-night-offline');
  await returnHome(page);
  await expectHomeScene(page, true);
  await allAssetsEmbedded();
  await showcase(page, 'portable-home-from-hk-offline');
  await expectClock(page, '19:45');
  await openAction(page, 'Open phone');
  await expect(page.locator('.phone-note-label')).toHaveText('Authored fictional story message');
  await expect(page.locator('.authored-phone-note .spoken-line')).toHaveText(junWords.home.hk.long);
  await page.getByRole('button', { name: 'Check the journey', exact: true }).click();
  await expect(page.locator('.route-note-condition')).toHaveText('Completed in this model');
  await expect(page.getByRole('button', { name: /^Coming home/ })).toContainText('completed');
  await allAssetsEmbedded();
  await closeDialogue(page);
  await expect(page.getByRole('textbox')).toHaveCount(0);

  await page.getByRole('button', { name: 'Try the other evening', exact: true }).click();
  await expectPhase(page, 'fork');
  await expectClock(page, '16:30');
  await expectSceneAssets(page, 'shenzhen-evening.webp', true);
  await openAction(page, 'Talk about dinner');
  await page.getByRole('button', { name: 'Change route', exact: true }).click();
  await page.getByRole('radio', { name: 'Bus via Lok Ma Chau road crossing', exact: true }).check();
  await expect(page.locator('.route-note-forecast')).toContainText('modeled home 23:15');
  await expect(page.locator('.route-loop-crossing')).toHaveText('Lok Ma Chau road crossing');
  await expect(page.getByLabel('Story clock', { exact: true })).toHaveText('16:30');
  await page.getByRole('button', { name: /^Going out/ }).click();
  await expect(page.locator('.route-note-legs li')).toHaveCount(3);
  await page.getByRole('button', { name: 'Hours and sources', exact: true }).click();
  await expect(page.locator('.route-note-detail')).toContainText('24 hours');
  await allAssetsEmbedded();
  await showcase(page, 'portable-route-road-offline');
  await page.getByRole('button', { name: 'Change route', exact: true }).click();
  await page.getByRole('radio', { name: 'Rail via Lo Wu', exact: true }).check();
  await expect(page.locator('.route-note-forecast')).toContainText('modeled home 22:15');
  await expect(page.locator('.route-loop-crossing')).toHaveText('Lo Wu rail crossing');
  await page.getByRole('button', { name: 'Back to Jun', exact: true }).click();
  await depart(page, 'Shenzhen');
  await expectSceneAssets(page, 'shenzhen-table.webp', true);
  await expectJun(page, true);
  await allAssetsEmbedded();
  await openAction(page, 'Open phone');
  await expect(page.locator('.route-note')).toContainText('Chosen route · read-only');
  await expect(page.getByRole('radio')).toHaveCount(0);
  await page.getByRole('button', { name: /^Coming home/ }).click();
  await expect(page.locator('.route-note-legs li')).toHaveCount(3);
  await expect(page.locator('.route-note-legs')).toContainText('return clearance allowance');
  await allAssetsEmbedded();
  await showcase(page, 'portable-route-rail-return-offline');
  await closeDialogue(page);
  await chooseDinner(page, 'simple');
  await expectSceneAssets(page, 'shenzhen-table.webp', true);
  await allAssetsEmbedded();
  await chooseWalk(page, 'short');
  await expectSceneAssets(page, 'sz-evening-night.webp', true);
  await expectJun(page, true);
  await allAssetsEmbedded();
  await closeDialogue(page);
  await showcase(page, 'portable-sz-night-offline');
  await returnHome(page);
  await expectHomeScene(page, true);
  await allAssetsEmbedded();
  await showcase(page, 'portable-home-from-sz-offline');
  await expectClock(page, '21:45');
  await allAssetsEmbedded();
  await page.reload();
  await startStory(page);
  await expectPhase(page, 'home');
  await expectHomeScene(page, true);
  await expectClock(page, '21:45');
  await openAction(page, 'Open phone');
  await expect(dialogue(page).getByRole('heading', { name: 'From Jun', exact: true })).toBeFocused();
  await expect(page.locator('.phone-note-label')).toHaveText('Authored fictional story message');
  await expect(page.locator('.authored-phone-note .spoken-line')).toHaveText(junWords.home.sz.short);
  await allAssetsEmbedded();
  await showcase(page, 'portable-home-note-sz-offline');
  const journey = page.getByRole('button', { name: 'Check the journey', exact: true });
  await journey.click();
  await expect(page.locator('.route-note-uncertainty')).toBeVisible();
  await expect(page.locator('.route-note-uncertainty')).toContainText(/entry.*unverified/i);
  await expect(page.getByRole('button', { name: /^Coming home/ })).toContainText('completed');
  await allAssetsEmbedded();
  await page.getByRole('button', { name: 'Back to the message', exact: true }).click();
  await expect(journey).toBeFocused();
  await page.getByRole('button', { name: 'Put the phone away', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Open phone', exact: true })).toBeFocused();

  await openOptions(page);
  await page.getByRole('button', { name: 'Reconsider the walk', exact: true }).click();
  await openAction(page, 'Step outside');
  await page.getByRole('button', { name: /^Let’s head home now\./ }).click();
  await expectHomeScene(page, true);
  await expectClock(page, '21:30');
  await allAssetsEmbedded();
  await showcase(page, 'portable-direct-home-offline');
  await openAction(page, 'Open phone');
  await expect(page.locator('.authored-phone-note .spoken-line')).toHaveText(junWords.direct);
  await page.getByRole('button', { name: 'Check the journey', exact: true }).click();
  await page.getByRole('button', { name: 'Evening assumptions', exact: true }).click();
  await expect(page.locator('.route-note-detail')).toContainText('No walk · chosen direct return');
  await allAssetsEmbedded();
  await closeDialogue(page);

  await openAction(page, 'Open wallet');
  await page.getByRole('button', { name: 'Who benefits from this spending?', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'What does tonight’s spending tell us about who gained?', exact: true })).toBeFocused();
  await expect(page.locator('.spending-context')).toContainText('HK$260.22 per person · HK$520.44 for 2 people (HKD)');
  await expect(page.locator('.spending-context')).toContainText('including transport');
  await page.locator('.surplus-lab > summary').click();
  await expect(page.getByLabel('Hypothetical pool · HKD', { exact: true })).toHaveValue('120');
  const membership = page.locator('.membership-lens');
  await expect(membership).toHaveJSProperty('open', false);
  await membership.locator(':scope > summary').click();
  await membership.getByRole('radio', { name: 'Worker decisions', exact: true }).check();
  await expect(membership.locator('.membership-reading > h3')).toHaveText('What decision rights do workers have?');
  await expect(membership.locator('.membership-reading-row')).toHaveCount(2);
  await expect(membership.locator('.membership-sources')).toHaveJSProperty('open', false);
  await expect(membership.locator('.membership-reading-row').nth(1).locator('.membership-limit')).toContainText('current admission or meeting rules were not verified');
  await membership.getByRole('radio', { name: 'Surplus', exact: true }).check();
  await expect(membership.locator('.membership-reading > h3')).toHaveText('Who has a documented claim on surplus?');
  await expect(membership.locator('.membership-reading-row').nth(1).locator('.membership-status')).toHaveText('Historical 2022 detail');
  await expect(membership.locator('.membership-reading-row').nth(1).locator('.membership-limit')).toContainText('current terms and audited finances were not verified');
  await expect(membership.locator('.membership-reading-row').nth(1).getByRole('link')).toHaveAttribute('href', 'https://cheeseboardcollective.coop/wp-content/uploads/2022/09/Collective-Hiring-Notice-202200930.pdf');
  await expect(page.getByLabel('Hypothetical pool · HKD', { exact: true })).toHaveValue('120');
  await expect(page.locator('.allocation-proof')).toContainText('HK$60.00 + HK$24.00 + HK$36.00 = HK$120.00');
  expect(requests).toEqual([]);
  await membership.locator(':scope > summary').click();
  // The desk has no bitmap images to decode; the request recorder still gates
  // the entire offline excursion, then every restored scene image is decoded.
  expect(requests).toEqual([]);
  await showcase(page, 'portable-business-context-offline', true);
  await page.getByRole('button', { name: 'Return to your evening', exact: true }).click();
  await expect(dialogue(page).getByRole('heading', { name: 'Wallet', exact: true })).toBeFocused();
  await closeDialogue(page);
  await expect(page.getByRole('button', { name: 'Open wallet', exact: true })).toBeFocused();
  await expectHomeScene(page, true);
  await expectClock(page, '21:30');
  await allAssetsEmbedded();

  await openAction(page, 'Open wallet');
  const beforeImport = await page.evaluate(() => ({
    story: localStorage.getItem('between-playable-v2'), plan: localStorage.getItem('between-journal-v1'),
  }));
  const useEvening = page.getByRole('button', { name: 'Use this evening in planner', exact: true });
  await useEvening.click();
  await expect(dialogue(page).getByRole('heading', { name: 'Use this evening in planner?', exact: true })).toBeFocused();
  await showcase(page, 'portable-planner-import-confirmation-offline');
  await page.getByRole('button', { name: 'Keep my plan', exact: true }).click();
  await expect(useEvening).toBeFocused();
  expect(await page.evaluate(() => ({ story: localStorage.getItem('between-playable-v2'), plan: localStorage.getItem('between-journal-v1') }))).toEqual(beforeImport);
  await useEvening.click();
  await page.getByRole('button', { name: 'Replace plan and explore', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Shape your evening', exact: true })).toBeVisible();
  await expect(page.getByLabel('Budget per person')).toHaveValue('400');
  await expect(page.locator('.party-field output')).toHaveText('2');
  await page.locator('.option-sz .outing-settings > summary').click();
  await expect(page.locator('.option-sz').getByLabel('Dinner in Shenzhen · minutes', { exact: true })).toHaveValue('60');
  await expect(page.locator('.option-sz').getByLabel('Wander in Shenzhen · minutes', { exact: true })).toHaveValue('0');
  await expect(page.locator('.option-sz').getByLabel('Authored scenario delay · minutes', { exact: true })).toHaveValue('30');
  expect(await page.evaluate(() => localStorage.getItem('between-playable-v2'))).toBe(beforeImport.story);
  expect(requests).toEqual([]);
  await startStory(page); await expectHomeScene(page, true);
  await expect(page.getByLabel('Story clock', { exact: true })).toHaveText('21:30');
  await allAssetsEmbedded();

  await openOptions(page);
  await page.getByRole('button', { name: 'Start a fresh evening', exact: true }).click();
  await page.getByRole('button', { name: 'Start a fresh story', exact: true }).click();
  await startStory(page);
  await expectPhase(page, 'fork');
  await expectClock(page, '16:30');
  await expectSceneAssets(page, 'hong-kong-evening.webp', true);
  await allAssetsEmbedded();
  await openPlanner(page);
  await expect(page.locator('.option-card')).toHaveCount(2);
  await page.getByLabel('Budget per person').fill('500');
  await page.locator('.option-hk').getByRole('button', { name: /Choose this kind of evening|Keep as a tentative choice/ }).click();
  await expect(page.getByRole('heading', { name: 'Your evening, pencilled in.' })).toBeVisible();
  await expect(page.getByRole('textbox')).toHaveCount(0);
  await allAssetsEmbedded();
  await showcase(page, 'portable-optional-plan-offline');
  expect(errors).toEqual([]);
  expect(requests).toEqual([]);
});
