import { test, expect } from '@playwright/test';
import { junWords } from './story-fixtures';
import {
  cityPreview, closeDialogue, dialogue, expectHomeScene, expectPhase, expectSceneAssets,
  openAction, openOptions, readStorySave, storyClock,
} from './story-helpers';

// These literal paths establish available controls and arithmetic for the two
// audience outcomes. They do not measure a ten-minute human pace or comprehension.
for (const city of ['hk', 'sz'] as const) {
  test(`presenter path ${city}: unseeded same-assumption previews lead through one evening to worker decisions`, async ({ page }) => {
    test.setTimeout(60_000);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('/');
    await expect(dialogue(page).getByRole('heading', { name: 'Dinner, then a walk?', exact: true })).toBeFocused();
    await expect(dialogue(page).locator('.spoken-line')).toHaveText(junWords.invitation);
    await page.getByRole('button', { name: 'Look around first', exact: true }).click();
    await openOptions(page);
    await page.locator('.story-setup > summary').click();
    const setupSummary = page.locator('.story-setup > p').first();
    await expect(setupSummary).toContainText('Room to wander');
    await expect(setupSummary).toContainText('16:30–23:30');
    await expect(setupSummary).toContainText('HK$400.00/person');
    await expect(page.getByRole('checkbox', { name: 'Include one fictional 30-minute dinner delay', exact: true })).toBeChecked();
    await closeDialogue(page);
    const initial = await readStorySave(page);
    expect(initial.baseInputs).toMatchObject({ origin: 'kowloon', partySize: 2, departureMinutes: 990, homeByMinutes: 1410, budgetPerPersonHKD: 400 });
    await openAction(page, 'Open wallet');
    await expect(dialogue(page).locator('.pocket-facts dd')).toHaveText(['HK$400.00', 'HK$304.00', 'HK$260.22']);
    await page.getByRole('button', { name: 'Put the wallet away', exact: true }).click();
    await cityPreview(page, 'Hong Kong').click();
    await openAction(page, 'Open phone');
    await expect(page.locator('.route-note-condition')).toHaveText('Conditional plan');
    await expect(page.locator('.route-note-forecast')).toHaveText('modeled home 19:15 · 4h 15m spare');
    await expect(page.getByRole('button', { name: /^Going out/ })).toContainText('16:30–16:45');
    await expect(page.getByRole('button', { name: /^Coming home/ })).toContainText('19:00–19:15');
    await expect(storyClock(page)).toHaveText('16:30');
    await page.getByRole('button', { name: 'Put the phone away', exact: true }).click();
    await cityPreview(page, 'Shenzhen').click();
    await openAction(page, 'Open phone');
    await expect(page.locator('.route-note')).toHaveAttribute('data-route', 'rail');
    await expect(page.locator('.route-note-selected')).toContainText('Rail via Lo Wu');
    await expect(page.locator('.route-note-forecast')).toHaveText('modeled home 22:15 · 1h 15m spare');
    await expect(page.getByRole('button', { name: /^Going out/ })).toContainText('1h 45m');
    await expect(page.getByRole('button', { name: /^Coming home/ })).toContainText('1h 45m');
    const assumptions = page.getByRole('button', { name: 'Evening assumptions', exact: true });
    await assumptions.click();
    await expect(page.locator('.route-note-detail')).toBeVisible();
    await expect(page.locator('.route-note-detail')).toContainText('60-minute simple dinner · assumed, still to choose');
    await expect(page.locator('.route-note-detail')).toContainText('45-minute walk · assumed, still to choose');
    await expect(page.locator('.route-note-detail')).toContainText('Includes the disclosed 30-minute dinner delay.');
    await expect(storyClock(page)).toHaveText('16:30');
    await assumptions.click();
    await page.getByRole('button', { name: 'Put the phone away', exact: true }).click();
    const previewed = await readStorySave(page);
    expect(previewed.baseInputs).toEqual(initial.baseInputs);
    expect(previewed.currentAttempt).toMatchObject({ phase: 'fork', city: null, dinnerChoice: null, walkChoice: null, route: 'rail' });
    if (city === 'hk') await cityPreview(page, 'Hong Kong').click();
    await openAction(page, 'Talk about dinner');
    const home = city === 'hk' ? '19:15' : '22:15';
    await expect(page.locator('.departure-forecast')).toContainText(`modeled home ${home}`);
    await page.getByRole('button', { name: city === 'hk' ? 'Head to the table' : 'Head to the station', exact: true }).click();
    await expectPhase(page, 'arrival');
    await expectSceneAssets(page, city === 'hk' ? 'hong-kong-table.webp' : 'shenzhen-table.webp');
    await expect(storyClock(page)).toHaveText(city === 'hk' ? '16:45' : '18:15');
    await page.getByRole('button', { name: 'Read the menu', exact: true }).click();
    await page.getByRole('button', { name: /^Let’s keep dinner simple\./ }).click();
    await expectPhase(page, 'afterDinner');
    await expect(storyClock(page)).toHaveText(city === 'hk' ? '18:15' : '19:45');
    await expect(page.locator('.play-event-note')).toContainText('added 30 minutes once');
    await page.getByRole('button', { name: 'Step outside', exact: true }).click();
    const longerWalk = page.getByRole('button', { name: /^Let’s take the longer walk\./ });
    await expect(longerWalk).toContainText('45 minutes');
    await expect(longerWalk).toContainText(`Home ${home}`);
    await longerWalk.click();
    await expectPhase(page, 'walk');
    await expectSceneAssets(page, city === 'hk' ? 'hk-evening-night.webp' : 'sz-evening-night.webp');
    await expect(storyClock(page)).toHaveText(city === 'hk' ? '19:00' : '20:30');
    await expect(dialogue(page).locator('.spoken-line').first()).toHaveText(junWords.walk[city].long);
    await page.getByRole('button', { name: 'Look around', exact: true }).click();
    await openAction(page, 'Head home');
    await page.getByRole('button', { name: 'Check the return route', exact: true }).click();
    await expect(page.getByRole('button', { name: /^Coming home/ })).toContainText(city === 'hk' ? '19:00–19:15' : '20:30–22:15');
    if (city === 'sz') await expect(page.locator('.route-note-uncertainty')).toContainText('entry eligibility, transport services, seats and queues remain unverified');
    await page.getByRole('button', { name: 'Back to Jun', exact: true }).click();
    await page.getByRole('button', { name: 'Follow the return journey', exact: true }).click();
    await expectHomeScene(page); await expect(storyClock(page)).toHaveText(home);
    await page.getByRole('button', { name: 'Finish the evening', exact: true }).click();
    await expect(dialogue(page)).not.toBeVisible();
    const completed = await readStorySave(page);
    expect(completed.currentAttempt).toMatchObject({ phase: 'home', city, dinnerChoice: 'simple', walkChoice: 'long' });
    await openAction(page, 'Open wallet');
    const each = city === 'hk' ? 'HK$304.00' : 'HK$260.22';
    const group = city === 'hk' ? 'HK$608.00' : 'HK$520.44';
    await expect(dialogue(page).locator('.pocket-facts dd')).toHaveText(['HK$400.00', each]);
    await page.getByRole('button', { name: 'Who benefits from this spending?', exact: true }).click();
    await expect(page.locator('.spending-context')).toContainText(`${each} per person · ${group} for 2 people (HKD)`);
    await expect(page.locator('.spending-context')).toContainText('including transport');
    const membership = page.locator('.membership-lens');
    await expect(membership).toHaveJSProperty('open', false);
    await membership.locator(':scope > summary').click();
    await membership.getByRole('radio', { name: 'Worker decisions', exact: true }).check();
    await expect(membership.locator('.membership-reading > h3')).toHaveText('What decision rights do workers have?');
    await expect(membership.locator('.membership-reading-row h4')).toHaveText(['Home Market · Hong Kong', 'The Cheese Board Collective · Berkeley']);
    await expect(membership.locator('.membership-reading-row').nth(0).locator('.membership-limit')).toContainText('does not mean workers have no voice');
    await expect(membership.locator('.membership-reading-row').nth(1).locator('.membership-status')).toContainText('historical 2022');
    await expect(membership.locator('.membership-reading-row').nth(1).locator('.membership-limit')).toContainText('current admission or meeting rules were not verified');
    await expect(membership.locator('.membership-sources')).toHaveJSProperty('open', false);
    await expect(page.locator('.surplus-lab')).toHaveJSProperty('open', false);
    expect(await readStorySave(page)).toEqual(completed);
    await membership.screenshot({ path: `artifacts/presenter-${city}-worker-decisions-390.png`, animations: 'disabled' });
  });
}
