'use strict';
(()=>{const host=document.getElementById('access');if(!host)return;let cards,chosen=0;const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const short=['Care','School','Visiting & working','Singapore–Johor'];
const routes=[
 {intro:'A subsidised follow-up pathway',items:[['Qualifying HA follow-up','Designated specialist or family-medicine follow-up'],['Corresponding Shenzhen clinic','HKU–Shenzhen Hospital; matching service category'],['Within the pilot’s scope','RMB2,000 annual subsidy cap; no inpatient or A&E coverage']],note:'Different programme from Elderly Health Care Vouchers. Co-payment and fee-waiver rules apply.'},
 {intro:'More than one allocation route',items:[['Discretionary places','Apply to one school; eligibility and selection rules apply'],['Central Allocation · Part A','Up to three unrestricted choices'],['Central Allocation · Part B','Dedicated commuter list, generally near boundary points']],note:'Part A and Part B belong to Central Allocation. They are not three successive hurdles. September 2027 admission guidance.'},
 {intro:'Two different permissions',items:[['Visiting Hong Kong','Eligible Shenzhen residents: one-year multiple-entry endorsement, up to seven days per stay'],['Employment in Hong Kong','Visitor status does not itself grant permission to work']],note:'The visitor route is not the same as an existing work entitlement. See the Immigration Department’s stated rules and exceptions.'},
 {intro:'Clearance is not work authorisation',items:[['At Singapore’s land checkpoints','QR clearance has eligibility rules. First-time foreign visitors or changed passports require passport presentation first.'],['For employment in Singapore','QR clearance does not itself grant permission to take a job']],note:'These are Singapore-side arrangements, not Malaysian entry rules or a measured end-to-end travel-time saving.'}
];
function render(){const card=cards[chosen],r=routes[chosen];document.getElementById('access-tabs').innerHTML=short.map((x,i)=>`<button data-access-card="${i}" aria-pressed="${i===chosen}">${x}</button>`).join('');document.getElementById('access-story').innerHTML=`<p class="access-jurisdiction">${escape(card.jurisdiction)}</p><h3>${escape(card.question||card.title)}</h3>${card.person?`<p class="access-person">${escape(card.person)}</p>`:''}<p>${escape(card.copy)}</p><p class="access-status">${escape(card.status)}</p><details><summary>Scope, exceptions & source documents</summary><h4>What the rules say</h4><ul>${(card.facts||[]).map(x=>`<li>${escape(x)}</li>`).join('')}</ul><h4>Scope limits</h4>${card.caveats.map(x=>`<p>${escape(x)}</p>`).join('')}${card.sources.map(x=>`<p><a href="${escape(x.url)}" target="_blank" rel="noopener noreferrer">${escape(x.publisher)}</a><br><small>${escape(x.locator)}</small></p>`).join('')}</details>`;document.getElementById('access-diagram').innerHTML=`<p class="access-diagram-title">${r.intro}</p><div class="policy-steps ${chosen===0?'sequential':'separate'}">${r.items.map((x,i)=>`<div class="policy-step"><span aria-hidden="true">${chosen===1?['D','A','B'][i]:i+1}</span><h4>${x[0]}</h4><p>${x[1]}</p></div>`).join('')}</div><p class="policy-diagram-note">${r.note}</p><p class="policy-diagram-unit">Schematic arrangement. Box sizes do not encode people or probabilities.</p>`;host.dataset.ready='true';}
document.getElementById('access-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-access-card]');if(b){chosen=+b.dataset.accessCard;render();window.atlasAnimate?.(document.getElementById('access-story'));window.atlasAnimate?.(document.getElementById('access-diagram'));document.querySelector(`[data-access-card="${chosen}"]`).focus({preventScroll:true});}});fetch('./data/access-cards.json').then(r=>{if(!r.ok)throw Error('Access sources unavailable');return r.json()}).then(d=>{cards=d.cards;render()}).catch(e=>{document.getElementById('access-story').innerHTML='<p role="alert">The policy evidence could not load. No eligibility rules have been substituted.</p>';console.error(e)});
})();
