'use strict';
(()=>{
const host=document.getElementById('atlas-maps');if(!host)return;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const R=6378137,rad=Math.PI/180;
const merc=([lon,lat])=>[R*lon*rad,R*Math.log(Math.tan(Math.PI/4+lat*rad/2))];
const regions={hk:{title:'Hong Kong–Shenzhen',subtitle:'Innovation parks and development areas.',bounds:[113.77,22.22,114.40,22.80],selected:'hetao_hk',color:'#8acfc0',dataRegion:'hk-shenzhen'},sg:{title:'Singapore–Johor',subtitle:'Economic-zone localities and a future rail link.',bounds:[103.35,1.14,104.38,1.86],selected:'woodlands_gateway',color:'#e8bd82',dataRegion:'singapore-johor'}};
let pack,anchors,bases,developments,schemes,refs;
const questions={hetao_hk:'Who will be able to work here, and how will they reach it?',hetao_sz:'Which arrangements let research, equipment and people move between the two parks?',qianhai:'How do service-sector opportunities reach households beyond the zone?',woodlands_gateway:'How will planned jobs and transport fit the routines of people living nearby?',rts_link:'What changes in a commuter’s day once access, queues and border checks are included?',js_sez:'Who can use the opportunities, who bears the costs, and who has a say?'};
function card(region){return `<article class="map-card" data-map="${region}"><div class="map-card-heading"><p class="eyebrow">${region==='hk'?'HONG KONG · MAINLAND CHINA':'SINGAPORE · MALAYSIA'}</p><h3>${regions[region].title}</h3><p>${regions[region].subtitle}</p></div><label class="map-select-label">Highlight a place<select aria-label="Highlight a place in ${regions[region].title}" data-place-select disabled><option>Loading places…</option></select></label><div class="map-canvas" data-map-canvas><p class="map-loading" role="status">Loading the map evidence…</p></div><p class="map-key">${region==='hk'?'<span class="key-area"></span> Dated planning area':'Zone boundaries not mapped'} <span class="key-point"></span> Locality marker · + = nearby places</p><div class="map-cluster-picker" data-map-cluster hidden></div><div class="map-details" data-map-details aria-live="polite"></div></article>`;}
function currentCard(k){return host.querySelector(`[data-map="${k}"]`);}
function geometryPath(g,project){const polygons=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];return polygons.map(poly=>poly.map(ring=>ring.map((p,i)=>{const[x,y]=project(p);return(i?'L':'M')+x.toFixed(2)+' '+y.toFixed(2)}).join('')+'Z').join('')).join('');}
function mapFeatures(k){let items=[];if(k==='hk'){
const loop=refs.features.find(f=>f.properties.plan_no==='S/LMCL/2');items.push({id:'hetao_hk',name:'Hetao Hong Kong Park / Loop',point:loop.geometry.coordinates,shape:schemes.features.find(f=>f.properties.PLAN_NO==='S/LMCL/2').geometry,geometryNote:'The outline is the 104ha statutory Loop scheme S/LMCL/2 (2018), not the 87ha park campus. The point is a label anchor computed from the scheme.',geometryUrl:'https://data.gov.hk/en-data/dataset/tpd-tpb1-digital-planning-data-of-statutory-plans'});
for(const f of developments.features){const id='nm_'+f.properties.OBJECTID;items.push({id,name:f.properties.Name,shape:f.geometry,geometryNote:'Official October 2023 development/study-area geography, metadata revised February 2025. This is not a current construction footprint.',geometryUrl:'https://portal.csdi.gov.hk/csdi-webpage/dataset/devb_plb_rcd_1701677887173_16270',area:f.properties.Area_ha,properties:f.properties});}}
const seen=new Set();for(const a of anchors.anchors.filter(a=>a.region===regions[k].dataRegion)){const id=a.related_evidence_feature_id;if(seen.has(id)||id==='hkstp_sz_branch')continue;seen.add(id);items.push({id,name:a.display_label,point:a.coordinates,geometryNote:a.scope_warning+' Locality marker only, not a development boundary or entrance.',geometryUrl:a.coordinate_source.url});}
if(k==='sg'){const a=refs.features.find(f=>f.properties.name==='Bukit Chagar RTS station');items.push({id:'rts_link',name:'RTS Link · Bukit Chagar locality',point:a.geometry.coordinates,geometryNote:'Approximate station locality from community map coordinates. No route alignment or travel-time area is drawn.',geometryUrl:a.properties.source_url});}
return items;}
function getEvidence(f){if(f.id.startsWith('nm_'))return{name:f.name,summary:'One of the Northern Metropolis’s ten mapped development or study areas in the October 2023 geography.',area_display:Math.round(f.area)+' ha',status:'historical_planning_geography',source_ids:['csdi_nm'],boundary_warning:f.geometryNote};return pack.features.find(x=>x.id===f.id);}
function statusText(s){const labels={operational_first_stage:'First stage open',expansion_planned:'Expansion planned',active:'Active',continuing_development:'Development continues',operating_policy_zone:'Operating policy zone',planned_phased_development:'Planned · phased',designated_flagship:'Designated flagship',project_status_varies:'Project status varies',testing_and_commissioning:'Testing and commissioning',not_passenger_operational:'Not open to passengers',historical_planning_geography:'October 2023 geography'};return s.split(';').map(x=>labels[x.trim()]||x.trim().replaceAll('_',' ')).join(' · ');}
function detail(k,feature){const f=getEvidence(feature);if(!f)return;const links=(f.source_ids||[]).slice(0,2).map(id=>pack.sources[id]).filter(Boolean);const area=f.area_display||(f.area_km2!=null?(f.area_km2<1?Math.round(f.area_km2*100)+' ha':f.area_km2.toLocaleString()+' km²'):null);const metric=feature.id==='rts_link'?'February 2027':area;currentCard(k).querySelector('[data-map-details]').innerHTML=`<p class="map-status">${escape(statusText(f.status))}</p><h4>${escape(f.name)}</h4>${metric?`<p class="map-metric">${escape(metric)}<span>${feature.id==='rts_link'?'conditional passenger-opening target':feature.id==='hetao_hk'?'campus land area':feature.id==='woodlands_gateway'?'maximum proposed district area':'source-defined area'}</span></p>`:''}<p>${f.kind==='js_sez_flagship'?'Policy incentive focus: ':''}${escape(f.summary)}${f.kind==='js_sez_flagship'?'. This is not a description of every activity in the locality.':''}</p>${feature.id==='hetao_hk'?'<p class="map-location-note">Outline: 104ha statutory scheme (2018), not the 87ha campus.</p>':feature.point?'<p class="map-location-note">Locality marker only. No project boundary is shown.</p>':''}<p class="map-human-question">${escape(questions[feature.id]||'How will the planned activity affect the people who live, work or care for someone nearby?')}</p><details><summary>What the map does and does not show</summary><p>${escape(feature.geometryNote)}</p>${f.boundary_warning?`<p>${escape(f.boundary_warning)}</p>`:''}<p><a href="${escape(feature.geometryUrl)}" target="_blank" rel="noopener noreferrer">Geometry / location source</a></p></details><p class="map-source-links">${links.map(l=>`<a href="${escape(l.url)}" target="_blank" rel="noopener noreferrer">${escape(l.publisher)}</a>`).join(' · ')}</p>`;}
function render(k){const region=regions[k],el=currentCard(k),canvas=el.querySelector('[data-map-canvas]'),w=Math.max(290,Math.round(canvas.clientWidth||560)),h=w<420?360:420,b=region.bounds,a=merc([b[0],b[1]]),z=merc([b[2],b[3]]),scale=Math.min((w-32)/(z[0]-a[0]),(h-45)/(z[1]-a[1])),cx=(a[0]+z[0])/2,cy=(a[1]+z[1])/2,project=p=>{const m=merc(p);return[w/2+(m[0]-cx)*scale,h/2-(m[1]-cy)*scale]};const items=mapFeatures(k),selected=items.find(f=>f.id===region.selected)||items[0];region.selected=selected.id;
let s=`<defs><clipPath id="map-clip-${k}"><rect x="1" y="1" width="${w-2}" height="${h-2}" rx="8"/></clipPath></defs><rect width="${w}" height="${h}" rx="8" fill="#142e38"/><g clip-path="url(#map-clip-${k})">`;
for(let i=1;i<6;i++)s+=`<line x1="${w*i/6}" y1="0" x2="${w*i/6}" y2="${h}" stroke="#32505b" stroke-width=".4"/><line x1="0" y1="${h*i/6}" x2="${w}" y2="${h*i/6}" stroke="#32505b" stroke-width=".4"/>`;
for(const f of bases[k].features){s+=`<path class="atlas-land" d="${geometryPath(f.geometry,project)}" fill="${f.properties.name==='Hong Kong'||f.properties.name==='Singapore'?'#395c61':'#2c4c56'}" stroke="#709098" stroke-width=".6" fill-rule="evenodd"/>`;}
// Geographic text anchors, not measured site points or legal centroids.
const regionLabels=k==='hk'?[{name:'SHENZHEN',point:[114.05,22.70]},{name:'HONG KONG',point:[114.13,22.39]}]:[{name:'JOHOR · MALAYSIA',point:[103.76,1.77]},{name:'SINGAPORE',point:[103.82,1.34]}];
for(const label of regionLabels){const[lx,ly]=project(label.point);s+=`<text x="${lx}" y="${ly}" text-anchor="middle" fill="#bfd6cd" font-size="${w<400?10:13}" letter-spacing="1.5">${label.name}</text>`;}
for(const f of items.filter(f=>f.shape)){const is=f.id===selected.id;s+=`<path class="atlas-area ${is?'is-selected':''}" data-place="${escape(f.id)}" tabindex="0" role="button" aria-label="${escape(f.name+'; dated planning outline')}" aria-pressed="${is}" d="${geometryPath(f.shape,project)}" fill="${is?'#f0c58b':'#85cabc'}" fill-opacity="${is?.65:.27}" stroke="${is?'#ffe0ac':'#83cdbb'}" stroke-width="${is?2:1}" fill-rule="evenodd"><title>${escape(f.name)}</title></path>`;}
const points=items.filter(f=>f.point).map((f,i)=>({f,index:i+1,xy:project(f.point)}));
const clusters=[];for(const p of points){let nearby=clusters.filter(c=>c.some(q=>Math.hypot(p.xy[0]-q.xy[0],p.xy[1]-q.xy[1])<31));if(!nearby.length)clusters.push([p]);else{const merged=[p,...nearby.flat()];for(const c of nearby)clusters.splice(clusters.indexOf(c),1);clusters.push(merged);}}
for(const cluster of clusters){const is=cluster.some(p=>p.f.id===selected.id),x=cluster.reduce((a,p)=>a+p.xy[0],0)/cluster.length,y=cluster.reduce((a,p)=>a+p.xy[1],0)/cluster.length;if(cluster.length>1){const ids=cluster.map(p=>p.f.id).join('|');s+=`<g class="atlas-pin atlas-cluster ${is?'is-selected':''}" data-cluster="${escape(ids)}" tabindex="0" role="button" aria-pressed="${is}" aria-label="${is?'Contains the selected place. ':''}${cluster.length} nearby places: ${escape(cluster.map(p=>p.f.name).join('; '))}. Open place picker."><title>${cluster.length} nearby places · select to choose</title><circle cx="${x}" cy="${y}" r="16" fill="${is?'#f0c58b':'#142e38'}" stroke="${is?'#fff1d9':region.color}" stroke-width="1.5"/><text x="${x}" y="${y+4}" text-anchor="middle" font-size="11" font-weight="700" fill="${is?'#142e38':region.color}">+${cluster.length}</text></g>`;}else{const p=cluster[0],f=p.f;s+=`<g class="atlas-pin ${is?'is-selected':''}" data-place="${escape(f.id)}" tabindex="0" role="button" aria-label="${escape(f.name+'; locality marker, not a boundary')}" aria-pressed="${is}"><title>${escape(f.name)}</title><circle cx="${x}" cy="${y}" r="${is?11:8}" fill="${is?'#f0c58b':region.color}" stroke="#142e38" stroke-width="2"/><text x="${x}" y="${y+3}" text-anchor="middle" font-size="9" font-weight="700" fill="#142e38">${p.index}</text><circle cx="${x}" cy="${y}" r="14" fill="#fff" fill-opacity="0" pointer-events="all"/></g>`;}}
s+='</g>';const scaleKm=k==='hk'?10:20,px=scaleKm*1000/Math.cos((b[1]+b[3])/2*rad)*scale;s+=`<path d="M20 ${h-26}v6h${px}v-6" fill="none" stroke="#e8e5d9" stroke-width="1.2"/><text x="20" y="${h-34}" fill="#d1ddd8" font-size="11">${scaleKm} km · approximate</text><text x="${w-20}" y="25" text-anchor="end" fill="#d1ddd8" font-size="11">N ↑</text>`;
canvas.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="group" aria-label="${escape(region.title)} regional overview. Generalised coastlines; dated planning polygons and approximate locality pins.">${s}</svg>`;
canvas.style.minHeight=h+'px';const sel=el.querySelector('[data-place-select]');sel.disabled=false;sel.innerHTML=items.map(f=>`<option value="${escape(f.id)}" ${f.id===region.selected?'selected':''}>${f.point?(items.filter(x=>x.point).findIndex(x=>x.id===f.id)+1)+' · ':'Area · '}${escape(f.name)}</option>`).join('');detail(k,selected);if(typeof normalizeText==='function')normalizeText(el);
}
function choose(k,id){regions[k].selected=id;render(k);window.atlasAnimate?.(currentCard(k).querySelector('[data-map-details]'));const picker=currentCard(k).querySelector('[data-map-cluster]');picker.hidden=true;picker.innerHTML='';}
function openCluster(k,ids,focus){const items=mapFeatures(k).filter(f=>ids.split('|').includes(f.id)),picker=currentCard(k).querySelector('[data-map-cluster]');picker.innerHTML='<p>Nearby places share one marker at this overview scale. Choose a place:</p>'+items.map(f=>`<button data-cluster-place="${escape(f.id)}">${escape(f.name)}</button>`).join('');picker.hidden=false;if(focus)picker.querySelector('button')?.focus();}
host.addEventListener('change',e=>{if(e.target.matches('[data-place-select]'))choose(e.target.closest('[data-map]').dataset.map,e.target.value);});
host.addEventListener('click',e=>{const cluster=e.target.closest('[data-cluster]');if(cluster){openCluster(cluster.closest('[data-map]').dataset.map,cluster.dataset.cluster,false);return;}const option=e.target.closest('[data-cluster-place]');if(option){const k=option.closest('[data-map]').dataset.map;choose(k,option.dataset.clusterPlace);currentCard(k).querySelector('select').focus({preventScroll:true});return;}const f=e.target.closest('[data-place]');if(f)choose(f.closest('[data-map]').dataset.map,f.dataset.place);});
host.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const cluster=e.target.closest('[data-cluster]');if(cluster){e.preventDefault();openCluster(cluster.closest('[data-map]').dataset.map,cluster.dataset.cluster,true);return;}const f=e.target.closest('[data-place]');if(f){e.preventDefault();const k=f.closest('[data-map]').dataset.map;choose(k,f.dataset.place);const target=host.querySelector(`[data-map="${k}"] [data-place="${f.dataset.place}"]`);(target||currentCard(k).querySelector('select')).focus({preventScroll:true});}});

let resizeTimer,lastMapWidth=window.innerWidth;window.addEventListener('resize',()=>{if(window.innerWidth===lastMapWidth)return;lastMapWidth=window.innerWidth;if(!pack)return;clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{render('hk');render('sg');},200);});
async function start(){try{const names=['map-evidence.json','map-place-anchors.json','map-hk-base.json','map-sg-base.json','map-hk-developments.json','map-hk-schemes.json','map-reference-points.json'];const d=await Promise.all(names.map(async n=>{const r=await fetch('./data/'+n);if(!r.ok)throw Error('Map source unavailable');return r.json();}));[pack,anchors]=d;bases={hk:d[2],sg:d[3]};developments=d[4];schemes=d[5];refs=d[6];host.innerHTML=card('hk')+card('sg');render('hk');render('sg');host.dataset.ready='true';}catch(e){host.innerHTML='<p class="map-error" role="alert">The map sources could not load. No boundaries or locations have been substituted.</p>';console.error(e);}}
host.innerHTML=card('hk')+card('sg');for(const el of host.querySelectorAll('[data-map-canvas]'))el.style.minHeight=(el.clientWidth<420?360:420)+'px';
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();start();}},{rootMargin:'250px'});observer.observe(host);}else start();
})();
