import { useState } from 'react';
import { Sparkles, Plus, Check } from 'lucide-react';
import { allocateSurplus } from '../domain/engine';
const exactCurrency = (amount: number | null) => amount === null ? 'Not yet known' : `HK$${amount.toLocaleString('en-HK', {minimumFractionDigits: 2, maximumFractionDigits: 2})}`;
export default function SurplusLab() {
  const [pool, setPool] = useState(120);
  const [weights, setWeights] = useState({worker: 50, community: 20, business: 30});
  const allocation = allocateSurplus(pool, weights);
  return <details className="surplus-lab"><summary><span className="surplus-icon"><Sparkles size={20}/></span><div><span className="eyebrow">AN OPTIONAL THOUGHT EXPERIMENT</span><h3>What if the same surplus were shared differently?</h3></div><Plus size={18}/></summary><div className="surplus-body"><p>Imagine a business already has a fixed distributable pool. Change who receives it. The total stays the same. This is separate from your outing bill and does not assume a different ownership model creates more money.</p><label className="field pool-field">Hypothetical pool · HKD<input type="number" min="0" max="100000" step="10" value={pool} onChange={e => setPool(Number(e.target.value))}/></label><div className="allocation-controls">{(['worker','community','business'] as const).map(key => <label className={`range-field allocation-${key}`} key={key} htmlFor={`allocation-${key}`}><span>{key === 'worker' ? 'Workers' : key === 'community' ? 'Community' : 'Business reserve'}<output>{allocation.allocations ? exactCurrency(allocation.allocations[key]) : '—'}</output></span><input id={`allocation-${key}`} type="range" min="0" max="100" value={weights[key]} onChange={e => setWeights({...weights,[key]:Number(e.target.value)})}/><small>Relative allocation weight: {weights[key]}</small></label>)}</div>{allocation.valid && allocation.allocations ? <><div className="allocation-bar" role="img" aria-label="Allocation of fixed hypothetical pool">{(['worker','community','business'] as const).map(key => <span key={key} className={key} style={{flex:allocation.allocationCents?.[key] || 0}}/>)}</div><p className="allocation-proof"><Check size={14}/> {exactCurrency(allocation.allocations.worker)} + {exactCurrency(allocation.allocations.community)} + {exactCurrency(allocation.allocations.business)} = {exactCurrency(allocation.poolHKD)}. The pool is conserved to the cent.</p></> : <p className="validation-error" role="alert">{allocation.errors.join(' ')}</p>}<p className="field-note">A rule for allocating a fixed pool is not evidence of higher productivity, wages or investment returns. Those require separate research.</p></div></details>;
}

